name: CPU tests

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-github:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-24.04]
          julia-version: ['lts', '1']
          julia-arch: [x64]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/install-juliaup@v2
        with:
          channel: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
